import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b bg-white">
          <nav className="max-w-5xl mx-auto px-4 py-3 flex items-center gap-4 text-sm">
            <Link href="/" className="font-semibold">Home</Link>
            <Link href="/instructions" className="hover:underline">Instructions</Link>
            <Link href="/admin" className="hover:underline">Admin</Link>
            <Link href="/moderation" className="hover:underline">Moderation Test</Link>
            <a href="http://localhost:8000/docs" target="_blank" rel="noopener noreferrer" className="ml-auto hover:underline">SLM API Docs</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
